'use strict';
(() => {
 const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), num=v=>Number.isFinite(v)?v.toLocaleString('en-GB'):'unknown';
 const titles=['Your Bitcoin connection','Browser access','Network & local data'];
 let snapshot=null,network=null,indexStatus=null,stage=0,working=false,previousFocus=null,readinessBusy=false,routingFailure=false;
 async function api(path,body){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),body?.action==='browser-routing'?120000:15000);try{const r=await fetch(path,{signal:ctl.signal,...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});const v=await r.json();if(!r.ok)throw Error(v.error||r.statusText);return v}finally{clearTimeout(timer)}}
 function error(e){$('setup-error').textContent=e.message||String(e);$('setup-error').hidden=false;}
 function readyControls(){ $('setup-next').disabled=working||routingFailure; $('setup-back').disabled=working||stage===0; }
 async function task(fn){if(working)return;working=true;$('setup-error').hidden=true;readyControls();try{await fn()}catch(e){error(e)}finally{working=false;readyControls()}}
 const checked=(id,label,value,note='')=>`<label class="check"><input type="checkbox" id="${id}" ${value?'checked':''}><span>${esc(label)}${note?`<small>${esc(note)}</small>`:''}</span></label>`;
 const toggle=(id,label,value,note='',locked=false)=>`<div><label class="index-switch"${locked?' title="Locked during Headers and Blocks testing"':''}><span>${esc(label)}</span><input type="checkbox" role="switch" id="${id}" ${value?'checked':''} ${locked?'disabled':''}${note?` aria-describedby="${id}-help"`:''}><span class="switch-track" aria-hidden="true"></span></label>${note?`<p id="${id}-help" class="small muted">${esc(note)}</p>`:''}</div>`;
 const field=(id,label,value,type='text')=>`<label class="field" for="${id}">${esc(label)}<input id="${id}" type="${type}" value="${esc(value??'')}"></label>`;
 const devMode=()=>sessionStorage.getItem('gateway.dev_mode')==='1';
 function renderNetwork(n){
  network=n;const h=n.headers||{};
  $('network-summary').textContent=`${n.enabled===false?'Outbound offline':'Bitcoin: '+num(n.connected||0)+' connections'} · Gateway peerhood: locked · Headers: ${h.header_state||'starting'}${indexStatus?' · '+num(indexStatus.localIndexes)+' local indexes · '+num(indexStatus.following)+' following new blocks · Gateway sharing locked':''}`;
  const warning=$('header-warning'),behind=Number.isFinite(h.header_target_height)&&Number.isFinite(h.header_height)&&h.header_target_height>h.header_height;
  if(warning)warning.hidden=!behind;
  const paused=n.headers_user_paused||(h.header_state==='paused'&&n.enabled!==false);$('headers-pause').textContent=paused?'Resume headers':'Pause headers';$('headers-pause').dataset.action=paused?'resume':'pause';
  const technical=devMode()?n:{enabled:n.enabled,bitcoin_connected:n.connected,gateway_connected:n.gateway_connected,headers:h};
  $('network-technical').textContent=JSON.stringify(technical,null,2);
  $('network-journey').innerHTML=`<p class="small muted">Bitcoin peers supply headers and requested blocks. Inspect individual peers and capabilities in Peers.</p>`;
  const speed=h.header_speed>0?`${num(Math.round(h.header_speed))} headers/s · `:'';
  $('header-progress').textContent=`${speed}${h.header_source?'Source '+h.header_source:'No header source yet'} · ${h.header_target_height>0?'peer target estimate '+num(h.header_target_height):'target estimate unavailable'}${h.header_bootstrap_state?' · bundled baseline '+h.header_bootstrap_state:''}${h.header_last_progress?' · last progress '+new Date(h.header_last_progress).toLocaleTimeString():''}`;
 }
 async function refreshReadiness(){if(readinessBusy||working||!snapshot||!$('gateway-setup').open||stage!==1)return;readinessBusy=true;try{const fresh=await api('/api/v1/setup');if(stage!==1||!$('gateway-setup').open)return;snapshot={...snapshot,browser:fresh.browser,system:fresh.system,native_host_registered:fresh.native_host_registered,progress:{...snapshot.progress,navigation_at:fresh.progress.navigation_at,navigation_address:fresh.progress.navigation_address}};renderBrowserState()}catch(e){if($('setup-browser-state'))$('setup-browser-state').textContent='Readiness unavailable: '+e.message}finally{readinessBusy=false}}
 async function poll(){try{renderNetwork(await api('/api/v1/network'));await refreshReadiness()}catch(e){$('network-summary').textContent='Connection status unavailable';$('header-progress').textContent=e.message}finally{setTimeout(poll,2500)}}
 function routingReady(){const sys=snapshot.system||{},installed=(snapshot.browser?.browsers||[]).filter(x=>x.installed);return !!sys.god_protocol&&!!sys.bitcoin_domain_rule&&installed.length>0&&installed.every(x=>x.native_registered)}
 function renderBrowserState(){
  if(!snapshot||!$('setup-browser-state'))return;const b=snapshot.browser||{},sys=snapshot.system||{},selected=$('setup-browser')?.value||snapshot.progress.browser,registration=(b.browsers||[]).find(x=>x.id===selected);
  const routed=routingReady();$('setup-routing').textContent=routed?'Repair Gateway browser routing':'Enable Gateway browser routing';$('setup-routing').disabled=working||sys.supported===false;
  $('setup-disable-routing').hidden=!(sys.god_protocol||sys.bitcoin_domain_rule||(b.browsers||[]).some(x=>x.native_registered));
  $('setup-routing-state').textContent=routed?'Native hosts, Gateway links and browser namespaces are registered.':`Gateway links: ${sys.god_protocol?'registered':'not registered'} · namespaces: ${sys.bitcoin_domain_rule?'registered':'not registered'}.`;
  $('setup-browser-list').innerHTML=(b.browsers||[]).map(x=>`<li><strong>${esc(x.name)}</strong> · ${!x.installed?'not detected':x.native_registered?'native host registered':'native host needs registration'}</li>`).join('');
  const p=snapshot.progress,delivered=p.navigation_at&&!p.navigation_at.startsWith('0001');
  $('setup-browser-state').textContent=b.native_active?`Authenticated native exchange observed${b.companion_browser?' ('+b.companion_browser+')':''}. ${delivered?'Latest companion delivery: '+p.navigation_address+'.':'Next: open 0.bitcoin from the companion and check its displayed resource.'}`:registration?.native_registered?'Next: load the companion in the selected browser profile, then open its toolbar panel and choose Open Gateway. Waiting for an authenticated native exchange.':'Next: enable browser routing to register the native host, then install the companion below.';
  $('setup-browser-fallback').textContent=({edge:'edge',brave:'brave',chrome:'chrome',chromium:'chrome'}[selected]||'chrome')+'://extensions/';
 }
 async function saveSettings(extra){const fresh=await api('/api/v1/settings');await api('/api/v1/settings',{...fresh.settings,...extra});snapshot.settings={...fresh.settings,...extra}}
 function coreVisibility(){const core=document.querySelector('[name="connection-mode"]:checked')?.value==='core';$('setup-core-options').hidden=!core;}
 function render(){
  if(!snapshot)return;const s=snapshot.settings,p=snapshot.progress,sys=snapshot.system||{},b=snapshot.browser||{};
  $('setup-step').textContent=`STEP ${stage+1} OF 3`;$('setup-title').textContent=titles[stage];$('setup-next').textContent=stage===2?'Save & open Gateway':'Save and continue';
  $('setup-index').innerHTML=titles.map((x,i)=>`<span class="${i===stage?'active':''}" ${i===stage?'aria-current="step"':''}>${i+1}. ${esc(x)}</span>`).join('');let content='';
  if(stage===0){const core=!s.core_disabled||!s.core_mount_disabled;
   content=`<p>Choose where Gateway gets Bitcoin headers and blocks. Other indexes are locked for later testing.</p><label class="setup-choice"><input type="radio" name="connection-mode" value="gateway" ${!core?'checked':''}><span class="connection-art gateway-art" aria-hidden="true">↗</span><span><strong>Gateway only</strong><small>Connect to Bitcoin peers and retrieve the data you need.</small></span></label><label class="setup-choice"><input type="radio" name="connection-mode" value="core" ${core?'checked':''}><span class="connection-art core-art" aria-hidden="true">₿</span><span><strong>Start with Bitcoin Core</strong><small>Use an existing local node or read its block files.</small></span></label><div id="setup-core-options"><p class="hint">${snapshot.core?.connected?'Bitcoin Core connected · height '+num(snapshot.core.height):snapshot.mounted_preparation?.block_files_found?'Existing block files found. Core RPC is not connected.':'Select your existing Core data directory. Gateway does not install Bitcoin Core.'}</p>${checked('setup-core-rpc','Connect to local Core RPC',!s.core_disabled)}${checked('setup-mount','Reuse existing Bitcoin block files read-only',!s.core_mount_disabled,'Existing files stay in place. This can work while Core is closed.')}<div class="form-grid">${field('setup-core-dir','Core data directory',s.bitcoin_data_dir)}${field('setup-block-dir','Optional block directory',s.bitcoin_blocks_dir)}${field('setup-rpc','Local Core RPC port',s.rpc_port||8332,'number')}</div>${checked('setup-prepare','Prepare block-file locations',s.prepare_mounted_files,'Scan selected files read-only so Gateway can locate blocks with Core closed. No block bodies are copied.')}<p class="small muted">${num(snapshot.core_store?.indexed_blocks||0)} block locations already indexed. Additional transaction indexes, inscriptions and sats remain locked. RPC authentication remains in Settings.</p>${s.prepare_mounted_files?'<button id="pause-mounted" type="button">Pause preparation</button>':''}</div>`;
  }
  if(stage===1)content=`<p>Browser integration is optional. Gateway’s address bar works without it.</p><section class="setup-access-step"><h3>1. Enable browser routing</h3><p>Register the native host for installed supported browsers, Gateway on-demand links, and routing for ${(b.namespaces||[{suffix:'.bitcoin'},{suffix:'.gateway'},{suffix:'.bitmap'}]).map(x=>'<strong>'+esc(x.suffix)+'</strong>').join(', ')}. Windows may request administrator approval for namespace routing.</p><div class="actions"><button id="setup-routing" type="button">Enable Gateway browser routing</button><button id="setup-disable-routing" type="button" hidden>Disable browser routing</button></div><p id="setup-routing-state" class="small muted"></p><ul id="setup-browser-list" class="small"></ul><div id="setup-routing-result" role="status"></div></section><section class="setup-access-step"><h3>2. Install the browser companion</h3><div class="form-grid"><label class="field" for="setup-browser">Browser<select id="setup-browser"><option value="chrome">Chrome</option><option value="edge">Edge</option><option value="brave">Brave</option><option value="chromium">Chromium</option></select></label>${field('setup-profile','Profile directory name',p.profile||'Default')}</div><p>Open Extensions, enable Developer mode, then choose Load unpacked.</p><button id="setup-open-browser" type="button">Copy extensions address & open browser</button><p id="setup-browser-launch" class="hint" role="status"></p><p class="small muted">Browsers require this address to be entered inside the browser. Paste <code id="setup-browser-fallback"></code> into that browser’s address bar. Use Default or a directory such as Profile 1.</p><p>Select the companion folder: <span class="mono">${esc(b.companion_path||'browser-companion')}</span></p><button id="setup-open-folder" type="button">Open companion folder</button></section><section class="setup-access-step"><h3>3. Open Gateway from the companion</h3><p>Open the companion toolbar panel, choose Open Gateway, then try <strong>0.bitcoin</strong>. A displayed resource verifies delivery.</p><p id="setup-browser-state" class="hint" aria-live="polite"></p><button id="setup-check-browser" type="button">Check readiness</button><p class="small muted">Readiness is checked automatically while this step is open. Checks never change registrations. Search recovery can happen after your search provider receives the address.</p></section>${checked('setup-startup','Start Gateway on sign-in',sys.run_on_startup,'A separate desktop choice. It does not enable browser routing or serving.')}${sys.supported===false?'<p class="hint">Native registration and the browser launcher are Windows-only in this release. Use Gateway in this browser and continue.</p>':''}`;
  if(stage===2)content=`<p>Choose your connection, cache and sharing preferences. Existing private objects stay private.</p><h3>Network & retention</h3>${checked('setup-network','Allow outbound Bitcoin connections',!s.network_disabled)}${checked('setup-cache','Cache retrieved blocks',s.cache_blocks)}<h3>Private cache</h3>${toggle('setup-private','Private cache',s.privacy_mode,'On keeps newly cached blocks private. Off allows new blocks to be shared when Bitcoin serving is on. Existing private blocks stay private.')}<h3>Peer serving</h3>${toggle('setup-serve','Serve Bitcoin data to Bitcoin peers',s.serve_data,'Serve available public blocks and headers. A ready full or pruned Bitcoin Core can provide full or recent-block service. Private cache objects are never shared.')}${toggle('setup-gateway-serve','🔒 Serve data to Gateway peers',false,'Locked during Headers and Blocks testing.',true)}<p class="small muted">Data folder: <span class="mono">${esc(snapshot.data_directory)}</span>. Headers and Bitcoin Blocks are available now; additional indexes stay locked. Direct peers can see your IP address and requested data.</p>`;
  $('setup-body').innerHTML=content;readyControls();
  if(stage===0){coreVisibility();document.querySelectorAll('[name="connection-mode"]').forEach(x=>x.onchange=coreVisibility);if($('pause-mounted'))$('pause-mounted').onclick=()=>task(async()=>{snapshot=await api('/api/v1/setup',{action:'pause-mounted'});render()});}
  if(stage===1){
   $('setup-browser').value=p.browser||'chrome';renderBrowserState();$('setup-browser').onchange=renderBrowserState;
   const configure=enabled=>task(async()=>{const result=await api('/api/v1/setup',{action:'browser-routing',enabled,consent:true});snapshot=result;routingFailure=!result.integration_result?.complete;renderBrowserState();$('setup-routing-result').innerHTML=(result.integration_result?.steps||[]).map(x=>`<p class="${x.success?'small':'setup-error'}">${esc(x.name)}: ${x.success?'saved':esc(x.error||'needs attention')}</p>`).join('')+(routingFailure?'<button id="setup-accept-partial" type="button">Keep partial browser access and continue</button>':'');if($('setup-accept-partial'))$('setup-accept-partial').onclick=()=>{routingFailure=false;readyControls()};});
   $('setup-routing').onclick=()=>configure(true);$('setup-disable-routing').onclick=()=>configure(false);
   $('setup-open-browser').onclick=()=>task(async()=>{let copied=false;try{await navigator.clipboard.writeText($('setup-browser-fallback').textContent);copied=true}catch{}await saveBrowser();try{await api('/api/v1/browser/open-setup',{browser:$('setup-browser').value,profile:$('setup-profile').value});$('setup-browser-launch').textContent=copied?'Extensions address copied. In the opened browser, press Ctrl+L, Ctrl+V, then Enter.':'Browser opened. Copy the displayed extensions address, paste it into the browser address bar, then press Enter.'}catch(e){throw Error(e.message+' Open '+$('setup-browser-fallback').textContent+' manually.')} });
   $('setup-open-folder').onclick=()=>task(async()=>{await api('/api/v1/browser/open-setup',{action:'folder',browser:$('setup-browser').value,profile:$('setup-profile').value})});
   $('setup-check-browser').onclick=()=>refreshReadiness();
  }

 }
 async function saveBrowser(){if(stage===1){const saved=await api('/api/v1/setup',{action:'save',flow_stage:stage,browser:$('setup-browser').value,profile:$('setup-profile').value.trim()});snapshot.progress=saved.progress;}}
 async function saveStage(){
  if(stage===0){const core=document.querySelector('[name="connection-mode"]:checked')?.value==='core';await saveSettings({core_disabled:!core||!$('setup-core-rpc').checked,core_mount_disabled:!core||!$('setup-mount').checked,prepare_mounted_files:core&&$('setup-mount').checked&&$('setup-prepare').checked,...(core?{bitcoin_data_dir:$('setup-core-dir').value.trim(),bitcoin_blocks_dir:$('setup-block-dir').value.trim(),rpc_port:Number($('setup-rpc').value)}:{})});}
  if(stage===1){await saveBrowser();if(snapshot.system?.supported&&$('setup-startup').checked!==snapshot.system.run_on_startup){const sys=await api('/api/v1/system/startup',{enabled:$('setup-startup').checked});snapshot.system=sys;}await api('/api/v1/setup',{action:'save',integration_reviewed:true});}
  if(stage===2)await saveSettings({network_disabled:!$('setup-network').checked,cache_blocks:$('setup-cache').checked,privacy_mode:$('setup-private').checked,serve_data:$('setup-serve').checked});
 }
 async function open(target){previousFocus=document.activeElement;try{snapshot=await api('/api/v1/setup');stage=snapshot.progress.flow_stage??(snapshot.progress.stage>=5?2:snapshot.progress.stage>=3?1:0);if(target==='browser')stage=1;routingFailure=false;$('setup-error').hidden=true;render();if(!$('gateway-setup').open)$('gateway-setup').showModal();if(!snapshot.progress.completed&&stage===0){$('gateway-setup').classList.add('setup-opening');setTimeout(()=>$('gateway-setup').classList.remove('setup-opening'),450)}$('setup-title').focus()}catch(e){$('header-progress').textContent=e.message}}
 function close(){ $('gateway-setup').close();previousFocus?.focus({preventScroll:true}); }
 document.addEventListener('click',e=>{if(e.target.closest('[data-gateway-setup]')){e.preventDefault();open(e.target.closest('[data-gateway-setup]').dataset.gatewaySetup)}});
 $('setup-close').onclick=()=>{if(!working)close()};$('gateway-setup').addEventListener('cancel',e=>{if(working)e.preventDefault();else previousFocus?.focus({preventScroll:true})});
 $('setup-back').onclick=()=>task(async()=>{await saveStage();stage=Math.max(0,stage-1);snapshot=await api('/api/v1/setup',{action:'save',flow_stage:stage});render();$('setup-title').focus()});
 $('setup-next').onclick=()=>task(async()=>{if(routingFailure)return;await saveStage();if(stage===2){snapshot=await api('/api/v1/setup',{action:'complete'});close();document.body.classList.add('gateway-entering');setTimeout(()=>document.body.classList.remove('gateway-entering'),350);window.dispatchEvent(new MessageEvent('message',{origin:location.origin,data:{type:'gateway:navigate',address:'.gateway'}}));return}stage++;snapshot=await api('/api/v1/setup',{action:'save',flow_stage:stage});render();$('setup-title').focus()});
 $('headers-pause').onclick=async()=>{try{await api('/api/v1/headers',{action:$('headers-pause').dataset.action||'pause'});renderNetwork(await api('/api/v1/network'))}catch(e){$('header-progress').textContent=e.message}};
 $('headers-retry').onclick=async()=>{try{await api('/api/v1/headers',{action:'retry'});renderNetwork(await api('/api/v1/network'))}catch(e){$('header-progress').textContent=e.message}};
 document.addEventListener('gateway:dev-mode',()=>{if(network)renderNetwork(network)});
 document.addEventListener('gateway:index-status',event=>{indexStatus=event.detail;if(network)renderNetwork(network)});
 poll();api('/api/v1/setup').then(s=>{snapshot=s;if(s.show_automatically||new URLSearchParams(location.search).get('setup')==='1')open()}).catch(()=>{});
})();
